CREATE TABLE mec_us_trp.sizmek_conversions_tags
(
   conversiontagid       bigint          NOT NULL ENCODE raw primary key,
   conversionname        varchar(300)    NOT NULL ENCODE raw,
   advertiserid          bigint          NOT NULL ENCODE raw references mec_us_trp.sizmek_advertisers(advertiserid),
   type                  varchar(150)    NOT NULL ENCODE raw,
   pageurl               varchar(6000) ENCODE raw,
   creationdate          timestamp ENCODE raw,
   group1                varchar(600) ENCODE raw,
   group2                varchar(600) ENCODE raw,
   group3                varchar(600) ENCODE raw,
   group4                varchar(600) ENCODE raw,
   group5                varchar(600) ENCODE raw,
   string1               varchar(300) ENCODE raw,
   string2               varchar(300) ENCODE raw,
   string3               varchar(300) ENCODE raw,
   string4               varchar(300) ENCODE raw,
   string5               varchar(300) ENCODE raw,
   string6               varchar(300) ENCODE raw,
   string7               varchar(300) ENCODE raw,
   string8               varchar(300) ENCODE raw,
   string9               varchar(300) ENCODE raw,
   string10              varchar(300) ENCODE raw,
   string11              varchar(300) ENCODE raw,
   string12              varchar(300) ENCODE raw,
   string13              varchar(300) ENCODE raw,
   string14              varchar(300) ENCODE raw,
   string15              varchar(300) ENCODE raw,
   string16              varchar(300) ENCODE raw,
   string17              varchar(300) ENCODE raw,
   string18              varchar(300) ENCODE raw,
   string19              varchar(300) ENCODE raw,
   string20              varchar(300) ENCODE raw,
   string21              varchar(300) ENCODE raw,
   string22              varchar(300) ENCODE raw,
   string23              varchar(300) ENCODE raw,
   string24              varchar(300) ENCODE raw,
   string25              varchar(300) ENCODE raw,
   string26              varchar(300) ENCODE raw,
   string27              varchar(300) ENCODE raw,
   string28              varchar(300) ENCODE raw,
   string29              varchar(300) ENCODE raw,
   string30              varchar(300) ENCODE raw,
   string31              varchar(300) ENCODE raw,
   string32              varchar(300) ENCODE raw,
   string33              varchar(300) ENCODE raw,
   string34              varchar(300) ENCODE raw,
   string35              varchar(300) ENCODE raw,
   string36              varchar(300) ENCODE raw,
   string37              varchar(300) ENCODE raw,
   string38              varchar(300) ENCODE raw,
   string39              varchar(300) ENCODE raw,
   string40              varchar(300) ENCODE raw,
   string41              varchar(300) ENCODE raw,
   string42              varchar(300) ENCODE raw,
   string43              varchar(300) ENCODE raw,
   string44              varchar(300) ENCODE raw,
   string45              varchar(300) ENCODE raw,
   string46              varchar(300) ENCODE raw,
   string47              varchar(300) ENCODE raw,
   string48              varchar(300) ENCODE raw,
   string49              varchar(300) ENCODE raw,
   creationdate_localtz  timestamp ENCODE raw
)
DISTSTYLE ALL
;